# Generated by Django 4.2.2 on 2023-06-23 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_alter_collection_feature_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="feature_product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="store.product",
            ),
        ),
    ]
