# Generated by Django 4.2.2 on 2023-06-23 05:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_alter_collection_feature_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collection",
            old_name="feature_product",
            new_name="featured_product",
        ),
    ]
