# Generated by Django 4.2.3 on 2023-07-09 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_customer_store_custo_last_na_2e448d_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Can cancel order')]},
        ),
    ]
